# Generated by Django 3.2.8 on 2021-10-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingrecord_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
