# Generated by Django 3.2.8 on 2021-10-22 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('listings', '0004_alter_listing_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
    ]
