# Generated by Django 3.2.8 on 2021-11-09 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('listings', '0006_auto_20211102_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
        migrations.RemoveField(
            model_name='listingrecord',
            name='series',
        ),
        migrations.DeleteModel(
            name='ListingRecordSeries',
        ),
        migrations.AddField(
            model_name='listingrecord',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listingsnapshot'),
        ),
    ]
