# Generated by Django 3.2.8 on 2021-10-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_shipping',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=models.FloatField(default=0),
        ),
    ]
