# Generated by Django 3.2.8 on 2021-10-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211020_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
